using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using HarmonyLib;
using Newtonsoft.Json.Linq;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Localization;

namespace AIInfluenceStoryMaster
{
    /// <summary>
    /// Writes Story Master's own encyclopedia layout into <c>Hero.EncyclopediaText</c>,
    /// with up to five sections drawn from the character's persona:
    ///
    ///   ◆ 描述      (CharacterDescription — editable freely in the editor)
    ///   ◆ 背景      (AIGeneratedBackstory)
    ///   ◆ 性格      (AIGeneratedPersonality)
    ///   ◆ 認知風格  (AIGeneratedCognitiveStyle — opt-in)
    ///   ◆ 語言癖好  (AIGeneratedSpeechQuirks — opt-in)
    ///
    /// AI Influence's native path (<c>CharacterInfo.UpdateEncyclopediaDescription</c>)
    /// only ever writes backstory + personality — players who author a description
    /// in the editor would never see it in game, which is why we format the text
    /// ourselves instead of triggering the mod's writer.
    ///
    /// Because the mod rewrites its own two-field layout whenever it (re)loads an
    /// NPC context (interaction, persona generation, its Content Editor saves), a
    /// Harmony postfix on that method re-applies our layout right after — so the
    /// player always sees our format, no matter who wrote last.
    ///
    /// Which sections appear (and whether we write at all) comes from MCM; see
    /// <see cref="SettingsBridge.Cfg"/>. With the master switch off, both the sync
    /// and the postfix become no-ops and the page is left entirely to AI Influence.
    ///
    /// Undo
    /// ----
    /// <c>Hero.EncyclopediaText</c> is serialised into the save
    /// (<c>AutoGeneratedSaveManager</c> registers it), so turning the feature off
    /// does *not* bring the original text back — an explicit restore is required.
    /// <see cref="CaptureOriginal"/> records each page before the first overwrite
    /// and <see cref="RestoreOriginals"/> puts them back; see that method for the
    /// three tiers and why dead heroes are treated differently.
    ///
    /// Everything AI-Influence-facing is reflection + try/catch: if a future
    /// version renames the type/method we log once, the postfix simply never
    /// attaches, and the session-launch sync still covers non-interacted heroes.
    /// </summary>
    internal static class EncyclopediaSync
    {
        // Character files are "<Name> (<StringId>).json"; the id in the trailing
        // parens is the anchor (names change with title/language, ids do not).
        private static readonly Regex FileIdRe =
            new Regex(@"\(([^()]+)\)\.json$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

        /// <summary>Persona fields, in the order they appear on the page.</summary>
        private static readonly string[] FieldKeys =
        {
            "CharacterDescription",
            "AIGeneratedBackstory",
            "AIGeneratedPersonality",
            "AIGeneratedCognitiveStyle",
            "AIGeneratedSpeechQuirks",
        };

        /// <summary>Section headings, parallel to <see cref="FieldKeys"/>.</summary>
        private static readonly string[] FieldTitles =
        {
            "{=StoryMaster_Enc_Desc}— Description —",
            "{=StoryMaster_Enc_Backstory}— Backstory —",
            "{=StoryMaster_Enc_Personality}— Personality —",
            "{=StoryMaster_Enc_Cognitive}— Cognitive style —",
            "{=StoryMaster_Enc_Speech}— Speech —",
        };

        /// <summary>File name holding the pre-overwrite pages, under the campaign's
        /// <c>storytools/</c> folder (so it travels with that campaign's data).</summary>
        private const string OriginalsFile = "encyclopedia_original.json";

        private static bool _reflectionFailedLogged;
        private static bool _patchAttempted;
        private static bool _standDownLogged;

        /// <summary>UTC stamp of the last successful sync, per campaign folder, so a
        /// session-launch sync only revisits files edited since. Cleared on game restart.</summary>
        private static readonly Dictionary<string, DateTime> LastSync =
            new Dictionary<string, DateTime>(StringComparer.OrdinalIgnoreCase);

        /// <summary>Latest file-sourced persona per StringId, for the postfix: when
        /// AI Influence rewrites a hero's entry we re-apply our layout using its
        /// (freshest) backstory/personality plus the fields only we know.</summary>
        private static readonly Dictionary<string, string[]> PersonaCache =
            new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);

        /// <summary>Originals recorded this session, keyed by StringId. Loaded lazily
        /// from <see cref="OriginalsFile"/> and written back after each capture.</summary>
        private static Dictionary<string, string> _originals;
        private static string _originalsFolder;

        // ── Public entry points ─────────────────────────────────────────────

        /// <summary>
        /// Apply the layout for every character whose JSON has any selected field.
        /// </summary>
        /// <param name="force">Ignore the "changed since last sync" filter.</param>
        /// <returns>Heroes updated, or -1 when the sync could not run.</returns>
        public static int Sync(bool force = false)
        {
            try
            {
                var cfg = SettingsBridge.Current;
                if (!cfg.WritesEncyclopedia) return 0;   // master switch off → leave the page alone
                if (Campaign.Current == null) return -1;
                string folder = ExportBehavior.ResolveFolder();
                if (string.IsNullOrEmpty(folder)) return -1;

                string dir = Path.Combine(FileContract.AiSaveDataDir, folder);
                if (!Directory.Exists(dir)) return -1;

                DateTime since = DateTime.MinValue;
                if (!force) LastSync.TryGetValue(folder, out since);

                var heroesById = BuildHeroIndex();
                int synced = 0;

                foreach (string file in Directory.GetFiles(dir, "*.json", SearchOption.TopDirectoryOnly))
                {
                    try
                    {
                        Match m = FileIdRe.Match(Path.GetFileName(file));
                        if (!m.Success) continue;
                        string stringId = m.Groups[1].Value;

                        bool fresh = force || File.GetLastWriteTimeUtc(file) > since;
                        string text = File.ReadAllText(file);
                        if (!ProbeHasContent(text)) continue;

                        string[] persona = TryReadFields(text);
                        if (persona == null) continue;

                        // Cache even when not fresh: the postfix needs the fields
                        // for heroes the mod touches mid-session.
                        PersonaCache[stringId] = persona;

                        if (!fresh) continue;
                        Hero hero;
                        if (!heroesById.TryGetValue(stringId, out hero) || hero == null) continue;
                        if (ApplyLayout(hero, persona, cfg)) synced++;
                    }
                    catch (Exception exFile)
                    {
                        FileContract.Log("EncyclopediaSync: skipped " + Path.GetFileName(file)
                                         + " — " + exFile.Message);
                    }
                }

                FlushOriginals();
                LastSync[folder] = DateTime.UtcNow;
                FileContract.Log("EncyclopediaSync: refreshed " + synced + " hero(es)"
                                 + (force ? " (full)" : " (changed only)") + ".");
                return synced;
            }
            catch (Exception ex)
            {
                FileContract.Log("EncyclopediaSync.Sync ERROR: " + ex.Message);
                return -1;
            }
        }

        /// <summary>
        /// Attach the keep-our-layout postfix to AI Influence's encyclopedia writer.
        /// Safe to call repeatedly; runs once. No-op when AI Influence is absent or
        /// the method moved (logged once).
        /// </summary>
        public static void TryInstallPatch(Harmony harmony)
        {
            if (_patchAttempted) return;
            _patchAttempted = true;
            try
            {
                Type t = AccessTools.TypeByName("AIInfluence.CharacterInfo");
                MethodInfo target = t == null ? null : t.GetMethod(
                    "UpdateEncyclopediaDescription",
                    BindingFlags.Public | BindingFlags.Static | BindingFlags.NonPublic,
                    null, new[] { typeof(Hero), typeof(string), typeof(string) }, null);
                if (target == null)
                {
                    FileContract.Log("EncyclopediaSync: CharacterInfo.UpdateEncyclopediaDescription "
                                     + "not found — layout postfix not installed.");
                    return;
                }
                harmony.Patch(target, postfix: new HarmonyMethod(
                    typeof(EncyclopediaSync).GetMethod(nameof(AfterModWrite),
                        BindingFlags.NonPublic | BindingFlags.Static)));
                FileContract.Log("EncyclopediaSync: layout postfix installed.");
            }
            catch (Exception ex)
            {
                FileContract.Log("EncyclopediaSync.TryInstallPatch ERROR: " + ex.Message);
            }
        }

        // ── Harmony postfix ─────────────────────────────────────────────────

        /// <summary>Re-apply our layout right after AI Influence writes its own
        /// (backstory+personality only) version.  The patch args carry the freshest
        /// persona; the description comes from our file-scan cache.</summary>
        private static void AfterModWrite(Hero hero, string backstory, string personality)
        {
            try
            {
                if (hero == null) return;
                var cfg = SettingsBridge.Current;
                // Master switch off: do nothing at all, so what the mod just wrote
                // is exactly what the player sees — its native two-field layout.
                if (!cfg.WritesEncyclopedia)
                {
                    // Log it once. When a player reports "the mod's persona does not
                    // show with Story Master's layout disabled", this line is what
                    // separates the two possible causes: present means AI Influence
                    // did write and the page is entirely its own business; absent
                    // means the mod never wrote in the first place.
                    if (!_standDownLogged)
                    {
                        _standDownLogged = true;
                        FileContract.Log("EncyclopediaSync: AI Influence wrote an encyclopedia "
                                         + "entry (" + (hero.Name == null ? "?" : hero.Name.ToString())
                                         + "); our layout is off, leaving it untouched.");
                    }
                    return;
                }

                string[] cached;
                PersonaCache.TryGetValue(hero.StringId ?? "", out cached);
                // The patch args carry the freshest backstory/personality; the other
                // three fields only exist in our cache.
                var persona = new string[FieldKeys.Length];
                if (cached != null) Array.Copy(cached, persona, FieldKeys.Length);
                persona[1] = backstory;
                persona[2] = personality;
                if (ApplyLayout(hero, persona, cfg))
                    // Persist here too: this path fires mid-session (an interaction,
                    // a persona generation) and Sync — the only other flush — may not
                    // run again before the player quits, which would lose the captured
                    // original for exactly the heroes they just talked to.
                    FlushOriginals();
            }
            catch { /* a postfix must never break the host mod */ }
        }

        // ── Layout ──────────────────────────────────────────────────────────

        /// <summary>Compose and write the selected sections. Sections with no content
        /// are omitted; a hero with nothing to show at all is left untouched.</summary>
        private static bool ApplyLayout(Hero hero, string[] persona, SettingsBridge.Cfg cfg)
        {
            bool[] want =
            {
                cfg.EncIncludeDescription,
                cfg.EncIncludeBackstory,
                cfg.EncIncludePersonality,
                cfg.EncIncludeCognitiveStyle,
                cfg.EncIncludeSpeechQuirks,
            };

            var sb = new StringBuilder();
            for (int i = 0; i < FieldKeys.Length; i++)
                if (want[i]) AppendSection(sb, FieldTitles[i], persona[i]);
            if (sb.Length == 0) return false;

            // Record what was there before we first replace it — the page is saved
            // into the .sav, so this file is the only faithful way back.
            CaptureOriginal(hero);
            hero.EncyclopediaText = new TextObject(sb.ToString(), null);
            return true;
        }

        private static void AppendSection(StringBuilder sb, string keyedTitle, string body)
        {
            if (string.IsNullOrWhiteSpace(body)) return;
            if (sb.Length > 0) sb.Append("\n\n");
            sb.Append(new TextObject(keyedTitle, null).ToString());
            sb.Append('\n');
            sb.Append(Sanitize(body.Trim()));
        }

        /// <summary>Player-authored text goes through TextObject, which parses
        /// braces as variables — swap them for fullwidth lookalikes so free-form
        /// descriptions can never break the encyclopedia page.</summary>
        private static string Sanitize(string s)
        {
            return s.Replace('{', '｛').Replace('}', '｝');
        }

        // ── File reading ────────────────────────────────────────────────────

        private static bool ProbeHasContent(string text)
        {
            foreach (string field in FieldKeys)
            {
                string key = "\"" + field + "\"";
                int i = text.IndexOf(key, StringComparison.Ordinal);
                if (i < 0) continue;
                int colon = text.IndexOf(':', i + key.Length);
                if (colon < 0) continue;
                int j = colon + 1;
                while (j < text.Length && char.IsWhiteSpace(text[j])) j++;
                // A non-empty string value, i.e. not `null` and not `""`.
                if (j < text.Length && text[j] == '"' && j + 1 < text.Length && text[j + 1] != '"')
                    return true;
            }
            return false;
        }

        /// <summary>Read the five persona fields, or null when the file has none of
        /// them (parallel to <see cref="FieldKeys"/>; entries may be null).</summary>
        private static string[] TryReadFields(string jsonText)
        {
            try
            {
                JObject o = JObject.Parse(jsonText);
                var vals = new string[FieldKeys.Length];
                bool any = false;
                for (int i = 0; i < FieldKeys.Length; i++)
                {
                    vals[i] = (string)o[FieldKeys[i]];
                    if (!string.IsNullOrWhiteSpace(vals[i])) any = true;
                }
                return any ? vals : null;
            }
            catch { return null; }
        }

        // ── Original pages: capture and restore ─────────────────────────────

        /// <summary>Record a hero's page the first time we are about to replace it.
        ///
        /// Only the first value per hero is kept — later calls must not overwrite it
        /// with our own layout, which would make the record useless.
        ///
        /// And crucially, a page that *already is* our layout is never recorded at
        /// all. Players who ran 1.2.0 (which had no capture) come to 1.2.1 with our
        /// three-section text already on every page; recording that as "the original"
        /// made 〔還原為原生頁面〕 write our own format straight back, which is exactly
        /// what it is supposed to remove. Leaving the key absent lets the restore fall
        /// through to the XML / regenerate tiers instead.</summary>
        private static void CaptureOriginal(Hero hero)
        {
            try
            {
                string id = hero.StringId;
                if (string.IsNullOrEmpty(id)) return;
                var map = LoadOriginals();
                if (map == null || map.ContainsKey(id)) return;
                TextObject cur = hero.EncyclopediaText;
                string text = cur == null ? "" : (cur.ToString() ?? "");
                if (IsOurLayout(text)) return;
                // Store "" for an empty page: an absent key means "never captured",
                // and the two need to stay distinguishable on restore.
                map[id] = text;
                _originalsDirty = true;
            }
            catch { /* capture is best-effort; never break a sync over it */ }
        }

        /// <summary>True when *text* looks like a page Story Master wrote.
        ///
        /// Two signals, because the headings are localised and the game language may
        /// have changed since the text was written:
        ///   • any of our section headings, resolved in the current language;
        ///   • the shape of <see cref="AppendSection"/>'s heading — a line that is
        ///     exactly "— … —" — which nothing else on an encyclopedia page uses.
        /// A false positive only costs restore precision (it falls through to the
        /// next tier); a false negative writes our own layout back as "the original",
        /// which is the failure this exists to prevent.</summary>
        private static bool IsOurLayout(string text)
        {
            if (string.IsNullOrWhiteSpace(text)) return false;
            foreach (string keyed in FieldTitles)
            {
                string heading;
                try { heading = new TextObject(keyed, null).ToString(); }
                catch { continue; }
                if (!string.IsNullOrEmpty(heading)
                    && text.IndexOf(heading, StringComparison.Ordinal) >= 0)
                    return true;
            }
            // Shape check on the first non-empty line.
            foreach (string raw in text.Split('\n'))
            {
                string line = raw.Trim();
                if (line.Length == 0) continue;
                return line.Length > 2 && line[0] == '—' && line[line.Length - 1] == '—';
            }
            return false;
        }

        private static bool _originalsDirty;

        /// <summary>Record what a restore just put on the page as that hero's original.
        ///
        /// Two jobs. It makes the record truthful — after tier 2 or tier 3 the page
        /// *is* the original, so that is what should be on file. And it keeps a record
        /// present, which is what stops <see cref="CaptureOriginal"/> from recording
        /// the page again later.
        ///
        /// That second job is not theoretical: an earlier attempt deleted the record
        /// once it had been applied, reasoning that a spent undo token is worthless.
        /// The result was a self-renewing loop — with no record, the next sync
        /// captured whatever was on the page (including a mangled page from an
        /// earlier build) and wrote it straight back in as "the original".</summary>
        private static void Remember(Dictionary<string, string> map, string id, string text)
        {
            if (map == null || string.IsNullOrEmpty(id)) return;
            string existing;
            if (map.TryGetValue(id, out existing) && existing == text) return;
            map[id] = text;
            _originalsDirty = true;
        }

        private static Dictionary<string, string> LoadOriginals()
        {
            string folder = ExportBehavior.ResolveFolder();
            if (string.IsNullOrEmpty(folder)) return null;
            if (_originals != null && string.Equals(_originalsFolder, folder,
                                                    StringComparison.OrdinalIgnoreCase))
                return _originals;

            _originalsFolder = folder;
            _originals = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            try
            {
                string path = OriginalsPath(folder);
                if (File.Exists(path))
                {
                    JObject o = JObject.Parse(File.ReadAllText(path));
                    foreach (var kv in o)
                        _originals[kv.Key] = kv.Value == null ? "" : (string)kv.Value;
                }
            }
            catch (Exception ex)
            {
                FileContract.Log("EncyclopediaSync: could not read " + OriginalsFile
                                 + " — " + ex.Message);
            }
            return _originals;
        }

        private static string OriginalsPath(string folder)
        {
            return Path.Combine(FileContract.CampaignStorytoolsDir(folder), OriginalsFile);
        }

        /// <summary>Persist newly captured originals. Called once per sync rather than
        /// per hero, so a full sync costs one write.</summary>
        private static void FlushOriginals()
        {
            try
            {
                if (!_originalsDirty || _originals == null || _originalsFolder == null) return;
                var o = new JObject();
                foreach (var kv in _originals) o[kv.Key] = kv.Value;
                FileContract.AtomicWrite(OriginalsPath(_originalsFolder), o.ToString());
                _originalsDirty = false;
            }
            catch (Exception ex)
            {
                FileContract.Log("EncyclopediaSync: could not write " + OriginalsFile
                                 + " — " + ex.Message);
            }
        }

        /// <summary>
        /// Put every page we rewrote back to its original text, in three tiers:
        ///
        ///   1. the value <see cref="CaptureOriginal"/> recorded before the first
        ///      overwrite — exact, and the only tier that can reproduce text AI
        ///      Influence had already written before Story Master was installed;
        ///   2. the <c>text=</c> attribute from a module's XML — recovers the
        ///      hand-written background of pre-authored heroes;
        ///   3. <b>empty</b> — the authentic state of a hero that never had authored
        ///      text, which is most of them.
        ///
        /// Tier 3 clears the field rather than filling it, and that is deliberate:
        ///
        /// * <c>Hero.Deserialize</c> sets <c>EncyclopediaText</c> to
        ///   <c>TextObject.GetEmpty()</c> for every hero whose XML has no
        ///   <c>text=</c> attribute — empty *is* the original value;
        /// * nothing in the game reads <c>EncyclopediaText</c> to display it. The
        ///   sentence a vanilla page shows ("… is a member of the …") is produced by
        ///   the encyclopedia's own view model at render time, which is why an empty
        ///   field still shows a proper description;
        /// * <c>Hero.SetHeroEncyclopediaTextAndLinks</c> looks like the way to
        ///   reproduce that sentence, but it returns a template whose
        ///   <c>{LORD.FIRSTNAME}</c> / <c>{CLAN_NAME}</c> / <c>{REPUTATION}</c>
        ///   placeholders resolve against *global* text variables set moments
        ///   earlier. Stored and rendered later, they resolve to nothing — giving
        ///   "is a member of the , . … is a person." The game itself calls that
        ///   method and throws the result away, which is the tell.
        ///
        /// Dead heroes are skipped past tier 2 on purpose: the game replaces their
        /// page with an obituary (<c>KillCharacterAction.CreateObituary</c>), and
        /// clearing the field would erase it.
        /// </summary>
        /// <returns>Pages restored, or -1 when the restore could not run.</returns>
        public static int RestoreOriginals()
        {
            try
            {
                if (Campaign.Current == null) return -1;
                var map = LoadOriginals();
                var heroes = BuildHeroIndex();
                var xml = XmlEncyclopediaText.Load();

                int exact = 0, fromXml = 0, cleared = 0, skipped = 0, discarded = 0;
                // Records that turned out to be our own layout, not a real original.
                var stale = new List<string>();
                foreach (var kv in heroes)
                {
                    Hero hero = kv.Value;
                    if (hero == null) continue;
                    try
                    {
                        // Initialised because the && short-circuits when map is null,
                        // leaving the out parameter unassigned.
                        string original = null;
                        bool haveRecord = map != null && map.TryGetValue(kv.Key, out original);
                        // A record that is itself our layout is worse than no record:
                        // restoring it re-applies the very format being removed. Files
                        // written before this check existed can contain exactly that,
                        // so drop it here rather than trusting the file.
                        if (haveRecord && IsOurLayout(original))
                        {
                            haveRecord = false;
                            discarded++;
                            stale.Add(kv.Key);
                        }
                        if (haveRecord)
                        {
                            hero.EncyclopediaText = string.IsNullOrEmpty(original)
                                ? TextObject.GetEmpty()
                                : new TextObject(original, null);
                            exact++;
                            continue;
                        }

                        string fromFile;
                        if (xml.TryGetValue(kv.Key, out fromFile)
                            && !string.IsNullOrWhiteSpace(fromFile))
                        {
                            hero.EncyclopediaText = new TextObject(fromFile, null);
                            fromXml++;
                            Remember(map, kv.Key, fromFile);
                            continue;
                        }

                        // No record and no authored text → the original was empty.
                        // Safe for the living; for the dead it would wipe the obituary.
                        if (hero.IsDead)
                        {
                            skipped++;
                            continue;
                        }
                        hero.EncyclopediaText = TextObject.GetEmpty();
                        cleared++;
                        Remember(map, kv.Key, "");
                    }
                    catch (Exception exHero)
                    {
                        FileContract.Log("EncyclopediaSync.Restore: skipped " + kv.Key
                                         + " — " + exHero.Message);
                    }
                }

                // Drop the poisoned records (ours-as-original) and persist whatever
                // Remember() put in, so the file reflects the pages that now exist.
                if (map != null)
                {
                    foreach (string id in stale) map.Remove(id);
                    if (stale.Count > 0) _originalsDirty = true;
                    FlushOriginals();
                }

                // Force the next sync to redo everything, otherwise the "changed
                // since" filter would leave the restored pages in place while the
                // character files still hold the persona we just stopped showing.
                LastSync.Clear();
                FileContract.Log("EncyclopediaSync: restored " + (exact + fromXml + cleared)
                                 + " page(s) — " + exact + " exact, " + fromXml + " from XML, "
                                 + cleared + " cleared to the game default, "
                                 + skipped + " skipped (dead, no record)"
                                 + (discarded > 0 ? ", " + discarded + " poisoned record(s) discarded" : "")

                                 + ".");
                return exact + fromXml + cleared;
            }
            catch (Exception ex)
            {
                FileContract.Log("EncyclopediaSync.RestoreOriginals ERROR: " + ex.Message);
                return -1;
            }
        }

        private static Dictionary<string, Hero> BuildHeroIndex()
        {
            var map = new Dictionary<string, Hero>(StringComparer.OrdinalIgnoreCase);
            try
            {
                foreach (Hero h in Hero.AllAliveHeroes)
                    if (h != null && !string.IsNullOrEmpty(h.StringId)) map[h.StringId] = h;
                foreach (Hero h in Hero.DeadOrDisabledHeroes)
                    if (h != null && !string.IsNullOrEmpty(h.StringId) && !map.ContainsKey(h.StringId))
                        map[h.StringId] = h;
            }
            catch (Exception ex)
            {
                FileContract.Log("EncyclopediaSync.BuildHeroIndex ERROR: " + ex.Message);
                if (!_reflectionFailedLogged) _reflectionFailedLogged = true;
            }
            return map;
        }
    }
}
